name: Build unit kits

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Run kit builder
        run: python build_kits.py
      - name: Ensure repository stayed clean
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "Repository has unexpected changes after building kits:" >&2
            git status --short >&2
            exit 1
          fi
